import { mkdir, cp, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { SEO_CONFIG, publishedRecords, recordBySlug } from '../src/editorial/content.mjs';

const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
const abs = path => `${SEO_CONFIG.origin}${path}`;
const nav = `<header class="editorial-header"><a class="editorial-brand" href="/" aria-label="Tau Gamma Phi archive home"><span aria-hidden="true">τ</span><span><strong>TAU GAMMA PHI</strong><small>National history &amp; impact archive</small></span></a><nav aria-label="Editorial navigation"><a href="/news/">News &amp; reading</a><a href="/history/">History context</a><a href="/references/">References</a></nav></header>`;
const footer = `<footer class="editorial-footer"><div><strong>Tau Gamma Phi · public archive</strong><p>Editorial pages explain the archive and preserve source boundaries. They do not replace an authorized council publication process.</p></div><nav aria-label="Footer"><a href="/sitemap/">HTML sitemap</a><a href="/references/commissioning-context/">Commissioning context</a><a href="/#contribute">Contribute a correction</a></nav></footer>`;
const breadcrumb = items => `<nav class="breadcrumbs" aria-label="Breadcrumb"><ol>${items.map((item, i) => `<li>${i === items.length - 1 ? `<span aria-current="page">${esc(item.label)}</span>` : `<a href="${esc(item.href)}">${esc(item.label)}</a>`}</li>`).join('')}</ol></nav>`;
const head = ({ title, description, path, type='WebPage', noindex=false }) => `${nav}<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · Tau Gamma Phi archive</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${abs(path)}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${abs(path)}"><meta property="og:type" content="${type === 'CollectionPage' ? 'website' : 'article'}">${noindex ? '<meta name="robots" content="noindex,follow">' : ''}<link rel="stylesheet" href="/src/editorial/editorial.css"></head>`;
const schemas = ({ title, description, path, type='WebPage', breadcrumbs, record }) => {
  const base = { '@context':'https://schema.org', '@type': type, name:title, description, url:abs(path), isPartOf:{ '@type':'WebSite', name:SEO_CONFIG.siteName, url:abs('/') }, breadcrumb:{ '@type':'BreadcrumbList', itemListElement:breadcrumbs.map((item, position)=>({ '@type':'ListItem', position:position+1, name:item.label, item:abs(item.href) })) } };
  if (record?.eligibleForArticleSchema) Object.assign(base, { headline:record.title, image:abs(record.cover.src), author:{ '@type':'Organization', name:SEO_CONFIG.siteName }, publisher:{ '@type':'Organization', name:SEO_CONFIG.siteName }, dateModified:record.researchDate, inLanguage:'en' });
  return `<script type="application/ld+json">${JSON.stringify(base)}</script>`;
};
const layout = ({ title, description, path, content, crumbs, type='WebPage', noindex=false, record }) => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · Tau Gamma Phi archive</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${abs(path)}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${abs(path)}"><meta property="og:type" content="${record?.eligibleForArticleSchema ? 'article' : type === 'CollectionPage' ? 'website' : 'article'}">${record?.cover ? `<meta property="og:image" content="${abs(record.cover.src)}"><meta name="twitter:card" content="summary_large_image">` : ''}${noindex ? '<meta name="robots" content="noindex,follow">' : ''}<link rel="stylesheet" href="/src/editorial/editorial.css">${schemas({ title, description, path, type:record?.eligibleForArticleSchema ? 'Article' : type, breadcrumbs: crumbs, record })}</head><body>${nav}<main class="editorial-main">${breadcrumb(crumbs)}${content}</main>${footer}</body></html>`;
const card = record => `<article class="reading-card${record.cover ? ' reading-card-feature' : ''}">${record.cover ? `<img class="card-cover" src="${esc(record.cover.src)}" alt="${esc(record.cover.alt)}" loading="lazy">` : ''}<p class="kicker">${esc(record.section)}${record.pendingSources ? ' · Sources pending' : ''}</p><h2><a href="/stories/${esc(record.slug)}/">${esc(record.title)}</a></h2><p>${esc(record.description)}</p><a class="read-link" href="/stories/${esc(record.slug)}/">Read the full ${record.cover ? 'feature' : 'context'} <span aria-hidden="true">→</span></a></article>`;
const cite = text => esc(text).replace(/\[(\d+)\]/g, '<sup class="citation"><a href="#source-$1" aria-label="Go to source $1">[$1]</a></sup>');
const articleBody = record => record.body.map(part => `<section><h2>${esc(part.heading)}</h2>${part.paragraphs.map(p => `<p>${cite(p)}</p>`).join('')}</section>`).join('');
const estimateEvidence = record => record.estimateNotes?.length ? `<aside class="estimate-evidence" aria-label="Membership estimate evidence"><p class="kicker">ESTIMATE LABELS</p><h2>How to read the membership estimates</h2>${record.estimateNotes.map(note => `<div class="estimate-evidence-item"><p><strong>${esc(note.label)}</strong></p><p>${cite(note.text)} <span class="estimate-source-note">Source note ${cite(note.source)}</span></p></div>`).join('')}<p class="estimate-correction"><a class="read-link" href="${estimateCorrectionHref(record)}">Question this estimate?</a> <span>or</span> <a class="read-link" href="${estimateCorrectionHref(record)}">Suggest an evidence correction</a></p><p class="estimate-correction-note">Please identify the claim and include a public supporting reference. This opens your email client; it does not send automatically.</p></aside>` : '';
const estimateCorrectionHref = record => `mailto:hello@weforgeweb.com?subject=${encodeURIComponent(`Question this estimate: ${record.title}`)}&body=${encodeURIComponent(`Article: ${record.title} (${SEO_CONFIG.origin}/stories/${record.slug}/)\\n\\nPlease identify the estimate or claim you are questioning and provide a public supporting reference.`)}`;

await rm('dist', { recursive:true, force:true });
await mkdir('dist', { recursive:true });
await cp('index.html', 'dist/index.html');
// Copy only runtime source and public design assets. Research inventories and
// rights registers under assets/ are intentionally excluded from the public build.
await cp('src', 'dist/src', { recursive:true });
await cp('metadata.json', 'dist/metadata.json');
await mkdir('dist/news', { recursive:true });
await mkdir('dist/history', { recursive:true });
await mkdir('dist/references', { recursive:true });
await mkdir('dist/sitemap', { recursive:true });
await mkdir('dist/stories', { recursive:true });

const newsPath='/news/';
await writeFile('dist/news/index.html', layout({ title:'News & reading', description:'Public editorial explainers and source-aware reading for the Tau Gamma Phi archive.', path:newsPath, type:'CollectionPage', crumbs:[{label:'Home',href:'/'},{label:'News & reading',href:newsPath}], content:`<header class="page-intro"><p class="kicker">PUBLIC READING ROOM</p><h1>News &amp; reading</h1><p>Read explainers about the archive and its evidence boundaries. Unapproved drafts and dynamic Firestore records are not silently published here; an approved static ingestion and rebuild is required before a permanent story route exists.</p></header><div class="reading-grid">${publishedRecords.map(card).join('')}</div>` }));
const history = recordBySlug('about-this-public-archive');
await writeFile('dist/history/index.html', layout({ title:'History context', description:'Context pages for the public history archive, with approval boundaries kept visible.', path:'/history/', type:'CollectionPage', crumbs:[{label:'Home',href:'/'},{label:'History context',href:'/history/'}], content:`<header class="page-intro"><p class="kicker">HISTORY &amp; CONTEXT</p><h1>History context</h1><p>These pages explain how to read the archive. They are editorial context, not chapter news or official council notices.</p></header><div class="reading-grid">${card(history)}${card(recordBySlug('research-context'))}</div>` }));
for (const record of publishedRecords) {
  const path=`/stories/${record.slug}/`;
  await mkdir(`dist/stories/${record.slug}`, { recursive:true });
  const sources = record.sources.map(s => `<li id="source-${s.n ?? ''}"><a href="${esc(s.href)}" target="_blank" rel="noreferrer">[${s.n ?? ''}] ${esc(s.label)}</a></li>`).join('');
  const related = record.related.map(slug => recordBySlug(slug)).filter(Boolean).map(card).join('');
  const feature = record.cover ? `<figure class="feature-cover"><img src="${esc(record.cover.src)}" alt="${esc(record.cover.alt)}"><figcaption>${esc(record.cover.caption)}</figcaption></figure><div class="feature-meta"><span class="kicker">Reviewed research feature</span><span>Research prepared ${esc(record.researchDate)} · No publication date asserted</span></div>` : '';
  const callout = record.callout ? `<aside class="key-finding"><p class="kicker">${esc(record.callout.label)}</p><p>${esc(record.callout.text)}</p></aside>` : '';
  const quality = record.sourceQuality ? `<p class="source-quality"><strong>How to read the sources:</strong> ${esc(record.sourceQuality)}</p>` : '';
  await writeFile(`dist/stories/${record.slug}/index.html`, layout({ title:record.title, description:record.description, path, record, crumbs:[{label:'Home',href:'/'},{label:'News & reading',href:'/news/'},{label:record.title,href:path}], content:`<article class="reader">${feature}<p class="kicker">${esc(record.section)}</p><h1>${esc(record.title)}</h1><p class="reader-dek">${esc(record.description)}</p>${callout}<p class="reader-note">This feature is based on public research prepared ${esc(record.researchDate)}. It is not a current membership census, an official national endorsement, or a substitute for an authorized directory.</p>${estimateEvidence(record)}${articleBody(record)}<aside class="source-trail"><h2>Source trail &amp; limits</h2>${quality}<ol>${sources}</ol></aside></article><section class="related"><h2>Related context</h2><div class="reading-grid">${related}</div></section>` }));
}
const refs = [
  ['commissioning-context','Commissioning context','National scope is the editorial frame; local commissioning credit and council context do not establish national authorization.'],
  ['verification-standards','Verification and evidence standards','The archive uses source review, corroboration, approval, and publication states. Pending material is not represented as verified.'],
  ['research-context','Research context','Research-stage material is clearly labeled sources pending and excluded from official news schema and publication claims.']
];
for (const [slug,title,description] of refs) {
  await mkdir(`dist/references/${slug}`, { recursive:true });
  await writeFile(`dist/references/${slug}/index.html`, layout({ title, description, path:`/references/${slug}/`, crumbs:[{label:'Home',href:'/'},{label:'References',href:'/references/'},{label:title,href:`/references/${slug}/`}], content:`<article class="reader"><p class="kicker">REFERENCE CONTEXT</p><h1>${esc(title)}</h1><p class="reader-dek">${esc(description)}</p><p>This reference page is maintained as context for readers and reviewers. It does not create a new official fact, byline, date, or chapter announcement.</p><p><a class="read-link" href="/news/">Return to news &amp; reading →</a></p></article>` }));
}
await writeFile('dist/references/index.html', layout({ title:'References', description:'Source trail and governance context for the Tau Gamma Phi public archive.', path:'/references/', type:'CollectionPage', crumbs:[{label:'Home',href:'/'},{label:'References',href:'/references/'}], content:`<header class="page-intro"><p class="kicker">SOURCE TRAIL</p><h1>References</h1><p>Read the context pages that explain commissioning boundaries, verification states, and research-stage material.</p></header><div class="reading-grid">${refs.map(([slug,title,description])=>`<article class="reading-card"><h2><a href="/references/${slug}/">${esc(title)}</a></h2><p>${esc(description)}</p></article>`).join('')}</div>` }));
const publicPaths=['/','/news/','/history/','/references/','/sitemap/', ...publishedRecords.map(r=>`/stories/${r.slug}/`), ...refs.map(([slug])=>`/references/${slug}/` )];
await writeFile('dist/sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${publicPaths.map(path=>`<url><loc>${abs(path)}</loc></url>`).join('')}</urlset>\n`);
await writeFile('dist/robots.txt', `User-agent: *\nAllow: /\nSitemap: ${SEO_CONFIG.origin}/sitemap.xml\n`);
await writeFile('dist/sitemap/index.html', layout({ title:'HTML sitemap', description:'Human-readable index of public, canonical archive pages.', path:'/sitemap/', type:'CollectionPage', crumbs:[{label:'Home',href:'/'},{label:'HTML sitemap',href:'/sitemap/'}], content:`<header class="page-intro"><p class="kicker">PUBLIC URL INDEX</p><h1>HTML sitemap</h1><p>Only public canonical pages are listed. Drafts, query-reader states, hashes, and private portals are excluded.</p></header><ul class="sitemap-list">${publicPaths.map(path=>`<li><a href="${path}">${path === '/' ? 'Home' : path}</a></li>`).join('')}</ul>` }));
console.log(`build passed: static site plus ${publishedRecords.length} editorial routes generated`);
