import { mkdir, cp, rm, writeFile, readFile, access } from 'node:fs/promises';
import { join, basename } from 'node:path';
import { SEO_CONFIG, publishedRecords, recordBySlug } from '../src/editorial/content.mjs';
import { notableProfiles } from '../src/notables.mjs';
import { renderHistoryPage, founders, renderFounderCard } from '../src/editorial/founders-content.mjs';

const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
const abs = path => `${SEO_CONFIG.origin}${path}`;

// Optional portrait handoff: publish only exact approved records whose mapped
// public_copy_path exists. The manifest uses `assets`, `status`, and
// `public_copy_path`; do not infer a filename from a profile name.
const portraitMap = new Map();
try {
  const raw = JSON.parse(await readFile('assets/research/personality-portraits/manifest.json', 'utf8'));
  const records = Array.isArray(raw) ? raw : (raw.assets || raw.profiles || raw.records || raw.portraits || []);
  for (const record of records) {
    const id = record.id || record.profileId || record.slug;
    const approved = String(record.status || '').toLowerCase() === 'approved' && record.permission_needed !== true;
    const relative = record.public_copy_path;
    const file = relative ? basename(relative) : '';
    if (!id || !approved || !relative || !/^[a-z0-9][a-z0-9._-]*\.webp$/i.test(file)) continue;
    const normalized = relative.replaceAll('\\', '/').replace(/^\.\//, '');
    const servedPath = `/${normalized}`;
    try { await access(join('.', normalized)); portraitMap.set(id, servedPath); } catch { /* exact approved asset is absent */ }
  }
} catch { /* no portrait handoff; initials remain the honest fallback */ }
const portraitFor = profile => portraitMap.get(profile.id);
const portraitMarkup = (profile, className = 'personality-portrait') => portraitFor(profile)
  ? `<img class="${className}" src="${portraitFor(profile)}" alt="Portrait of ${esc(profile.name)}" width="800" height="1000" style="height:auto" loading="lazy" decoding="async">`
  : `<div class="${className} personality-monogram" aria-label="Portrait unavailable for ${esc(profile.name)}">${esc(profile.initials)}</div>`;
const nav = `<header class="editorial-header"><a class="editorial-brand" href="/" aria-label="Tau Gamma Phi archive home"><img src="/src/assets/brand/seal-512.png" alt="Tau Gamma Phi official seal" width="44" height="44" decoding="async"><span><strong>TAU GAMMA PHI</strong><small>National history &amp; impact archive</small></span></a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="editorial-nav">Menu</button><nav id="editorial-nav" aria-label="Editorial navigation"><details><summary>Explore</summary><div class="nav-dropdown"><a href="/news/">News &amp; Updates</a><a href="/history/">History</a><a href="/personalities/">Personalities</a></div></details><details><summary>Sources</summary><div class="nav-dropdown"><a href="/references/">References</a><a href="/references/commissioning-context/">Commissioning context</a></div></details></nav><script type="module">import { initHeaderNavigation } from '/src/header-navigation.mjs'; initHeaderNavigation({ root: document.querySelector('#editorial-nav'), menuToggle: '.editorial-header .menu-toggle' });</script></header>`;
const footer = `<footer class="editorial-footer"><div><strong>Tau Gamma Phi · public archive</strong><p>Public research and source-aware context for history, service, and community memory. This archive does not replace authorized council publication.</p><div class="footer-crest-pair"><figure><img src="/src/assets/branding/tau-gamma-phi-limbaga-road-chapter-crest.webp" alt="Tau Gamma Phi Limbaga Road Chapter crest" width="96" height="96" loading="lazy"><figcaption>Limbaga Road Chapter</figcaption></figure><figure><img src="/src/assets/branding/zamboanga-city-triskelion-council-crest.webp" alt="Zamboanga City Triskelion Council crest" width="96" height="86" loading="lazy"><figcaption>Zamboanga City Council</figcaption></figure></div><p class="commissioning-credit">Commissioned by Limbaga Road Chapter, Pasonanca &middot; Triskelion de Zamboanga Council, Zamboanga City.<br><a href="https://www.facebook.com/TGPZCC" target="_blank" rel="noreferrer">Zamboanga City Council on Facebook ↗</a><br><small>Commissioning context is not national endorsement or official approval.</small></p></div><nav aria-label="Footer"><a href="/sitemap/">HTML sitemap</a><a href="/references/commissioning-context/">Commissioning context</a><a href="/#contribute">Contribute a correction</a></nav></footer>`;
const breadcrumb = items => `<nav class="breadcrumbs" aria-label="Breadcrumb"><ol>${items.map((item, i) => `<li>${i === items.length - 1 ? `<span aria-current="page">${esc(item.label)}</span>` : `<a href="${esc(item.href)}">${esc(item.label)}</a>`}</li>`).join('')}</ol></nav>`;
const head = ({ title, description, path, type='WebPage', noindex=false }) => `${nav}<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · Tau Gamma Phi archive</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${abs(path)}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${abs(path)}"><meta property="og:type" content="${type === 'CollectionPage' ? 'website' : 'article'}">${noindex ? '<meta name="robots" content="noindex,follow">' : ''}<link rel="stylesheet" href="/src/editorial/editorial.css"><link rel="stylesheet" href="/src/editorial/founders.css"><link rel="icon" href="/src/assets/brand/favicon.ico" sizes="any"><link rel="icon" type="image/png" sizes="32x32" href="/src/assets/brand/favicon-32.png"><link rel="apple-touch-icon" sizes="180x180" href="/src/assets/brand/seal-180.png"></head>`;
const schemas = ({ title, description, path, type='WebPage', breadcrumbs, record }) => {
  const base = { '@context':'https://schema.org', '@type': type, name:title, description, url:abs(path), isPartOf:{ '@type':'WebSite', name:SEO_CONFIG.siteName, url:abs('/') }, breadcrumb:{ '@type':'BreadcrumbList', itemListElement:breadcrumbs.map((item, position)=>({ '@type':'ListItem', position:position+1, name:item.label, item:abs(item.href) })) } };
  if (record?.eligibleForArticleSchema) Object.assign(base, { headline:record.title, image:abs(record.cover.src), author:{ '@type':'Organization', name:SEO_CONFIG.siteName }, publisher:{ '@type':'Organization', name:SEO_CONFIG.siteName }, dateModified:record.researchDate, inLanguage:'en' });
  return `<script type="application/ld+json">${JSON.stringify(base)}</script>`;
};
const layout = ({ title, description, path, content, crumbs, type='WebPage', noindex=false, record }) => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · Tau Gamma Phi archive</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${abs(path)}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${abs(path)}"><meta property="og:type" content="${record?.eligibleForArticleSchema ? 'article' : type === 'CollectionPage' ? 'website' : 'article'}">${record?.cover ? `<meta property="og:image" content="${abs(record.cover.src)}"><meta name="twitter:card" content="summary_large_image">` : ''}${noindex ? '<meta name="robots" content="noindex,follow">' : ''}<link rel="stylesheet" href="/src/editorial/editorial.css"><link rel="stylesheet" href="/src/editorial/founders.css"><link rel="icon" href="/src/assets/brand/favicon.ico" sizes="any"><link rel="icon" type="image/png" sizes="32x32" href="/src/assets/brand/favicon-32.png"><link rel="apple-touch-icon" sizes="180x180" href="/src/assets/brand/seal-180.png">${schemas({ title, description, path, type:record?.eligibleForArticleSchema ? 'Article' : type, breadcrumbs: crumbs, record })}</head><body>${nav}<main class="editorial-main">${breadcrumb(crumbs)}${content}</main>${footer}</body></html>`;
const card = record => `<article class="reading-card${record.cover ? ' reading-card-feature' : ''}">${record.cover ? `<img class="card-cover" src="${esc(record.cover.src)}" alt="${esc(record.cover.alt)}" loading="lazy">` : ''}<p class="kicker">${esc(record.section)}${record.pendingSources ? ' · Sources pending' : ''}</p><h2><a href="/stories/${esc(record.slug)}/">${esc(record.title)}</a></h2><p>${esc(record.description)}</p><a class="read-link" href="/stories/${esc(record.slug)}/">Read the full ${record.cover ? 'feature' : 'context'} <span aria-hidden="true">→</span></a></article>`;
const cite = text => esc(text).replace(/\[(\d+)\]/g, '<sup class="citation"><a href="#source-$1" aria-label="Go to source $1">[$1]</a></sup>');
const articleBody = record => record.body.map(part => `<section><h2>${esc(part.heading)}</h2>${part.paragraphs.map(p => `<p>${cite(p)}</p>`).join('')}</section>`).join('');
const estimateEvidence = record => record.estimateNotes?.length ? `<aside class="estimate-evidence" aria-label="Membership estimate evidence"><p class="kicker">ESTIMATE LABELS</p><h2>How to read the membership estimates</h2>${record.estimateNotes.map(note => `<div class="estimate-evidence-item"><p><strong>${esc(note.label)}</strong></p><p>${cite(note.text)} <span class="estimate-source-note">Source note ${cite(note.source)}</span></p></div>`).join('')}<p class="estimate-correction"><a class="read-link" href="${estimateCorrectionHref(record)}">Question this estimate?</a> <span>or</span> <a class="read-link" href="${estimateCorrectionHref(record)}">Suggest an evidence correction</a></p><p class="estimate-correction-note">Please identify the claim and include a public supporting reference. This opens your email client; it does not send automatically.</p></aside>` : '';
const estimateCorrectionHref = record => `mailto:hello@weforgeweb.com?subject=${encodeURIComponent(`Question this estimate: ${record.title}`)}&body=${encodeURIComponent(`Article: ${record.title} (${SEO_CONFIG.origin}/stories/${record.slug}/)\\n\\nPlease identify the estimate or claim you are questioning and provide a public supporting reference.`)}`;

const personalityCard = profile => `<article class="reading-card personality-card">${portraitMarkup(profile, 'personality-card-portrait')}<p class="kicker">${esc(profile.domain)} · ${profile.source ? 'Professional record linked' : 'Public record limited'}</p><h2><a href="/personalities/${esc(profile.id)}/">${esc(profile.name)}</a></h2><p>${esc(profile.summary)}</p><p class="personality-status">${profile.associationSource ? 'Association record linked separately' : 'Association remains unverified'}</p><a class="read-link" href="/personalities/${esc(profile.id)}/">View profile <span aria-hidden="true">→</span></a></article>`;
const personalitySchema = (profile, path) => `<script type="application/ld+json">${JSON.stringify({ '@context':'https://schema.org', '@type':'Person', name:profile.name, url:abs(path) })}</script>`;
const personalityPage = profile => {
  const path = `/personalities/${profile.id}/`;
  const professional = profile.source ? `<a href="${esc(profile.source.url)}" target="_blank" rel="noreferrer">${esc(profile.source.label)} ↗</a>` : '<span>Public professional source not attached.</span>';
  const association = profile.associationSource ? `<a href="${esc(profile.associationSource.url)}" target="_blank" rel="noreferrer">${esc(profile.associationSource.label)} ↗</a>` : '<span>Membership research pending; no official roster claim is made.</span>';
  return layout({ title:profile.name, description:`A source-aware public profile for ${profile.name}, with professional record and association evidence kept separate.`, path, crumbs:[{label:'Home',href:'/'},{label:'Personalities',href:'/personalities/'},{label:profile.name,href:path}], content:`<article class="reader personality-reader">${portraitMarkup(profile, 'personality-hero-portrait')}<p class="kicker">${esc(profile.domain)} · ${esc(profile.role)}</p><h1>${esc(profile.name)}</h1><p class="reader-dek">${esc(profile.summary)}</p><p class="reader-note">This is an editorial profile of a publicly listed personality. Professional achievements and Tau Gamma Phi association evidence are reviewed as separate records. Unverified fields are not presented as fact.</p><section><h2>About this person</h2><p>${esc(profile.summary)} ${profile.source ? `The linked professional record is the current public source used for the achievement summary.` : 'The public record is intentionally limited until an authoritative professional source is attached.'}</p></section><section><h2>Notable work or public record</h2><p>${esc(profile.role)} is the selected public-record focus for this profile. Specific dates, titles, or additional achievements are omitted where an authoritative source has not been attached.</p></section><section><h2>Evidence kept separate</h2><dl class="personality-evidence"><div><dt>Professional record</dt><dd>${professional}</dd></div><div><dt>Association record</dt><dd>${association}</dd></div></dl></section><aside class="source-trail"><h2>Source trail &amp; correction</h2><p class="source-quality">Source status is visible by design. The archive does not infer membership from occupation, public office, party-list naming, or association with another person.</p><p><a class="read-link" href="mailto:hello@weforgeweb.com?subject=${encodeURIComponent(`Correction for personality profile: ${profile.name}`)}">Suggest a source correction ↗</a></p></aside></article>${personalitySchema(profile,path)}` });
};

await rm('dist', { recursive:true, force:true });
await mkdir('dist', { recursive:true });
await cp('index.html', 'dist/index.html');
// Copy only runtime source and public design assets. Research inventories and
// rights registers under assets/ are intentionally excluded from the public build.
await cp('src', 'dist/src', { recursive:true });
await writeFile('dist/src/portrait-map.mjs', `// Generated from the approved portrait handoff; empty entries fall back to initials.\nexport const portraitMap = new Map(${JSON.stringify([...portraitMap])});\n`);
await cp('metadata.json', 'dist/metadata.json');
await mkdir('dist/news', { recursive:true });
await mkdir('dist/history', { recursive:true });
await mkdir('dist/references', { recursive:true });
await mkdir('dist/sitemap', { recursive:true });
await mkdir('dist/stories', { recursive:true });
await mkdir('dist/personalities', { recursive:true });

const newsPath='/news/';
await writeFile('dist/news/index.html', layout({ title:'News & reading', description:'Public editorial explainers and source-aware reading for the Tau Gamma Phi archive.', path:newsPath, type:'CollectionPage', crumbs:[{label:'Home',href:'/'},{label:'News & reading',href:newsPath}], content:`<header class="page-intro"><p class="kicker">PUBLIC READING ROOM</p><h1>News &amp; Updates</h1><p>Read public explainers and source-aware context. Material is published only after review; readers can follow each story’s references and limits.</p></header><div class="reading-grid">${publishedRecords.map(card).join('')}</div>` }));
await writeFile('dist/personalities/index.html', layout({ title:'Notable personalities', description:'A source-aware gallery of publicly listed Tau Gamma Phi personalities, with association evidence kept separate from career records.', path:'/personalities/', type:'CollectionPage', crumbs:[{label:'Home',href:'/'},{label:'Personalities',href:'/personalities/'}], content:`<header class="page-intro"><p class="kicker">PUBLIC PERSONALITY GALLERY</p><h1>Notable personalities</h1><p>A readable gallery of the 16 existing listed records. Select a profile to read a short public-record note. This is not an official membership roster or an endorsement list.</p></header><div class="reading-grid">${notableProfiles.map(personalityCard).join('')}</div>` }));
for (const profile of notableProfiles) {
  await mkdir(`dist/personalities/${profile.id}`, { recursive:true });
  await writeFile(`dist/personalities/${profile.id}/index.html`, personalityPage(profile));
}
await writeFile('dist/history/index.html', layout({ title:'Tau Gamma Phi history', description:'A source-cited history of Tau Gamma Phi founding context, growth, service, and contemporary anti-hazing responsibilities.', path:'/history/', type:'CollectionPage', crumbs:[{label:'Home',href:'/'},{label:'History',href:'/history/'}], content:renderHistoryPage() }));
for (const founder of founders) {
  const path = founder.profileHref;
  await mkdir(`dist${path}`, { recursive:true });
  await writeFile(`dist${path}index.html`, layout({ title:founder.name, description:`A bounded founder record for ${founder.name}, using the supplied historical research without invented biography or likeness.`, path, crumbs:[{label:'Home',href:'/'},{label:'History',href:'/history/'},{label:founder.name,href:path}], content:`<article class="reader founder-profile-reader"><div class="founder-profile-monogram" aria-label="Portrait unavailable for ${esc(founder.name)}">${esc(founder.initials)}</div><p class="kicker">Founding-generation research lead</p><h1>${esc(founder.name)}</h1><p class="reader-dek">The supplied research supports this short name as part of the founding-generation record.</p><p class="reader-note">Verified photographs are pending. No AI-generated face, fake likeness, or unlicensed portrait is used here. Identity, biography, and portrait rights remain subject to authorized confirmation.</p><p><a class="read-link" href="/history/">Read the source-cited history →</a></p></article>` }));
}
for (const record of publishedRecords) {
  const path=`/stories/${record.slug}/`;
  await mkdir(`dist/stories/${record.slug}`, { recursive:true });
  const sources = record.sources.map(s => `<li id="source-${s.n ?? ''}"><a href="${esc(s.href)}" target="_blank" rel="noreferrer">[${s.n ?? ''}] ${esc(s.label)}</a></li>`).join('');
  const related = record.related.map(slug => recordBySlug(slug)).filter(Boolean).map(card).join('');
  const feature = record.cover ? `<figure class="feature-cover"><img src="${esc(record.cover.src)}" alt="${esc(record.cover.alt)}"><figcaption>${esc(record.cover.caption)}</figcaption></figure><div class="feature-meta"><span class="kicker">Reviewed research feature</span><span>Research prepared ${esc(record.researchDate)} · No publication date asserted</span></div>` : '';
  const callout = record.callout ? `<aside class="key-finding"><p class="kicker">${esc(record.callout.label)}</p><p>${esc(record.callout.text)}</p></aside>` : '';
  const quality = record.sourceQuality ? `<p class="source-quality"><strong>How to read the sources:</strong> ${esc(record.sourceQuality)}</p>` : '';
  await writeFile(`dist/stories/${record.slug}/index.html`, layout({ title:record.title, description:record.description, path, record, crumbs:[{label:'Home',href:'/'},{label:'News & reading',href:'/news/'},{label:record.title,href:path}], content:`<article class="reader">${feature}<p class="kicker">${esc(record.section)}</p><h1>${esc(record.title)}</h1><p class="reader-dek">${esc(record.description)}</p>${callout}<p class="reader-note">This feature is based on public research prepared ${esc(record.researchDate)}. It is not a current membership census, an official national endorsement, or a substitute for an authorized directory.</p>${estimateEvidence(record)}${articleBody(record)}<aside class="source-trail"><h2>Source trail &amp; limits</h2>${quality}<ol>${sources}</ol></aside></article><section class="related"><h2>Related context</h2><div class="reading-grid">${related}</div></section>` }));
}
const refs = [
  ['commissioning-context','Commissioning context','National scope is the editorial frame; local commissioning credit and council context do not establish national authorization.'],
  ['verification-standards','Verification and evidence standards','The archive uses source review, corroboration, approval, and publication states. Pending material is not represented as verified.'],
  ['research-context','Research context','Research-stage material is clearly labeled sources pending and excluded from official news schema and publication claims.']
];
for (const [slug,title,description] of refs) {
  await mkdir(`dist/references/${slug}`, { recursive:true });
  await writeFile(`dist/references/${slug}/index.html`, layout({ title, description, path:`/references/${slug}/`, crumbs:[{label:'Home',href:'/'},{label:'References',href:'/references/'},{label:title,href:`/references/${slug}/`}], content:`<article class="reader"><p class="kicker">REFERENCE CONTEXT</p><h1>${esc(title)}</h1><p class="reader-dek">${esc(description)}</p><p>This reference page is maintained as context for readers and reviewers. It does not create a new official fact, byline, date, or chapter announcement.</p><p><a class="read-link" href="/news/">Return to news &amp; reading →</a></p></article>` }));
}
await writeFile('dist/references/index.html', layout({ title:'References', description:'Source trail and governance context for the Tau Gamma Phi public archive.', path:'/references/', type:'CollectionPage', crumbs:[{label:'Home',href:'/'},{label:'References',href:'/references/'}], content:`<header class="page-intro"><p class="kicker">SOURCE TRAIL</p><h1>References</h1><p>Read the context pages that explain commissioning boundaries, verification states, and research-stage material.</p></header><div class="reading-grid">${refs.map(([slug,title,description])=>`<article class="reading-card"><h2><a href="/references/${slug}/">${esc(title)}</a></h2><p>${esc(description)}</p></article>`).join('')}</div>` }));
const publicPaths=['/','/news/','/history/','/references/','/personalities/','/sitemap/', ...publishedRecords.map(r=>`/stories/${r.slug}/`), ...notableProfiles.map(profile=>`/personalities/${profile.id}/`), ...founders.map(founder=>founder.profileHref), ...refs.map(([slug])=>`/references/${slug}/` )];
await writeFile('dist/sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${publicPaths.map(path=>`<url><loc>${abs(path)}</loc></url>`).join('')}</urlset>\n`);
await writeFile('dist/robots.txt', `User-agent: *\nAllow: /\nSitemap: ${SEO_CONFIG.origin}/sitemap.xml\n`);
await writeFile('dist/sitemap/index.html', layout({ title:'HTML sitemap', description:'Human-readable index of public, canonical archive pages.', path:'/sitemap/', type:'CollectionPage', crumbs:[{label:'Home',href:'/'},{label:'HTML sitemap',href:'/sitemap/'}], content:`<header class="page-intro"><p class="kicker">PUBLIC URL INDEX</p><h1>HTML sitemap</h1><p>Only public canonical pages are listed. Drafts, query-reader states, hashes, and private portals are excluded.</p></header><ul class="sitemap-list">${publicPaths.map(path=>`<li><a href="${path}">${path === '/' ? 'Home' : path}</a></li>`).join('')}</ul>` }));
console.log(`build passed: static site plus ${publishedRecords.length} editorial routes generated`);
