// Public-figure research collection.
// Association status is intentionally distinct from professional-record sources.
// The supplied research file is not an official national membership roster.

const sourceReview = 'Association context: recorded in the supplied research collection. Primary affiliation link is still being normalized.';

export const notableProfiles = [
  { id: 'roy-ordinario', name: 'Roy Ordinario', initials: 'RO', domain: 'History', domainKey: 'history', role: 'Founding-generation record', summary: 'Included for historical significance in the fraternity’s originating generation at UP Diliman.', association: sourceReview, evidence: 'Research context · source link pending' },
  { id: 'errol-garchitorena', name: 'Errol Garchitorena Jr.', initials: 'EG', domain: 'Leadership', domainKey: 'leadership', role: 'National fraternity leadership', summary: 'The supplied research identifies a 2025–2027 National Premier term and a public-safety career.', association: sourceReview, evidence: 'Research context · source link pending' },
  { id: 'joel-villanueva', name: 'Joel Villanueva', initials: 'JV', domain: 'Public service', domainKey: 'public-service', role: 'National public service', summary: 'Included for a public career spanning the House of Representatives, TESDA, and the Senate.', association: sourceReview, evidence: 'Research context · source link pending' },
  { id: 'ralph-recto', name: 'Ralph G. Recto', initials: 'RR', domain: 'Public service', domainKey: 'public-service', role: 'Economic and public policy', summary: 'Included for a long national public-service career across Congress and executive roles.', association: sourceReview, evidence: 'Research context · source link pending' },
  { id: 'richard-gomez', name: 'Richard Frank Gomez', initials: 'RG', domain: 'Public service', domainKey: 'public-service', role: 'Public service and sport', summary: 'Included for a public record in entertainment, local government, Congress, and competitive shooting.', association: sourceReview, evidence: 'Research context · source link pending' },
  { id: 'jose-teves', name: 'Jose “Bong” J. Teves Jr.', initials: 'JT', domain: 'Public service', domainKey: 'public-service', role: 'Legislative public service', summary: 'Included for congressional service. A TGP Party-list seat is treated separately from personal fraternity association.', association: sourceReview, evidence: 'Research context · source link pending' },
  { id: 'rommel-marbil', name: 'Rommel Francisco D. Marbil', initials: 'RM', domain: 'Public service', domainKey: 'public-service', role: 'Public safety leadership', summary: 'Included for senior national police leadership described in the supplied research.', association: sourceReview, evidence: 'Research context · source link pending' },
  { id: 'vicente-danao', name: 'Vicente Dupa Danao Jr.', initials: 'VD', domain: 'Public service', domainKey: 'public-service', role: 'Public safety leadership', summary: 'Included for senior national police service and an officer-in-charge role recorded in the supplied research.', association: sourceReview, evidence: 'Research context · source link pending' },
  { id: 'vandolph-quizon', name: 'Vandolph Lacsamana Quizon', initials: 'VQ', domain: 'Culture', domainKey: 'culture', role: 'Entertainment and local government', summary: 'Included for a public record across film and television and local elected service.', association: sourceReview, evidence: 'Research context · source link pending' },
  { id: 'eumir-marcial', name: 'Eumir Felix Marcial', initials: 'EM', domain: 'Sport', domainKey: 'sport', role: 'Olympic boxing', summary: 'Tokyo Olympic bronze medalist in boxing. His professional achievement is independently documented; association context remains under source review.', association: sourceReview, evidence: 'Professional record linked · association source review', source: { label: 'Olympics.com athlete record', url: 'https://olympics.com/en/athletes/eumir-marcial' } },
  { id: 'raymond-almazan', name: 'Raymond Almazan', initials: 'RA', domain: 'Sport', domainKey: 'sport', role: 'Basketball', summary: 'Philippine national-team player listed by FIBA for the 2019 Basketball World Cup.', association: sourceReview, evidence: 'Professional record linked · association source review', source: { label: 'FIBA player record', url: 'https://www.fiba.basketball/en/players/235795-raymond-almazan' } },
  { id: 'john-riel-casimero', name: 'John Riel Reponte Casimero', initials: 'JC', domain: 'Sport', domainKey: 'sport', role: 'Professional boxing', summary: 'Included in the supplied research for a three-division world-championship boxing career.', association: sourceReview, evidence: 'Research context · source link pending' },
  { id: 'alvin-aguilar', name: 'Arthur Alvin A. Aguilar', initials: 'AA', domain: 'Sport', domainKey: 'sport', role: 'Combat-sport institution building', summary: 'United World Wrestling lists him as President of the Wrestling Association of the Philippines. A Supreme Court decision expressly identifies him as a Tau Gamma Phi member.', association: 'Association context: expressly identified as a Tau Gamma Phi member in a Philippine Supreme Court decision.', evidence: 'Judicial record and professional record linked', source: { label: 'United World Wrestling federation profile', url: 'https://cms.uww.org/about-uww/national-federation/wrestling-association-philippines' }, associationSource: { label: 'Supreme Court decision: DLSU v. Court of Appeals', url: 'https://lawphil.net/judjuris/juri2007/dec2007/gr_127980_2007.html' } },
  { id: 'jm-de-guzman', name: 'Juan Miguel “JM” Gob de Guzman', initials: 'JM', domain: 'Culture', domainKey: 'culture', role: 'Acting and music', summary: 'Included for an entertainment career and a chapter leadership description in the supplied research.', association: sourceReview, evidence: 'Research context · source link pending' },
  { id: 'luis-manzano', name: 'Luis Philippe Santos Manzano', initials: 'LM', domain: 'Culture', domainKey: 'culture', role: 'Television and film', summary: 'Included for a long-running public career in television and entertainment.', association: sourceReview, evidence: 'Research context · source link pending' },
  { id: 'nathan-azarcon', name: 'Nathan Peter Hachero Azarcon', initials: 'NA', domain: 'Culture', domainKey: 'culture', role: 'Music', summary: 'Included for work as a bassist and songwriter in Philippine rock music.', association: sourceReview, evidence: 'Research context · source link pending' }
];

export const notableDomains = [
  { key: 'all', label: 'All records' },
  { key: 'history', label: 'History' },
  { key: 'leadership', label: 'Leadership' },
  { key: 'public-service', label: 'Public service' },
  { key: 'sport', label: 'Sport' },
  { key: 'culture', label: 'Culture' }
];
